name: Create branch from issue

on:
  issues:
    types: [opened]

jobs:
  createBranch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Create branch
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        git checkout -b issue/${{ github.event.issue.number }}
        git push origin issue/${{ github.event.issue.number }}
